# ---------------------------------------------------------------------------
# Author: Vishnuu A
# Scope: full_sdlc
# Date: 2026-04-05
# ---------------------------------------------------------------------------
"""full_sdlc

Revision ID: 9ccc5f1342c6
Revises: ff812f04885c
Create Date: 2026-07-11 23:49:31.272659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9ccc5f1342c6'
down_revision: Union[str, None] = 'ff812f04885c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Function: upgrade
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("connector_type IN ('SERVICENOW', 'JIRA', 'GITHUB')", name='ck_connector_type'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'connector_type', name='uq_connector_project_type')
    )
    op.create_table('test_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('environments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entry_exit_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'SUSPECT')", name='ck_status'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_plan_citation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_plan_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('quoted_span', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_plan_id', 'chunk_id', name='uq_tpcitation_plan_chunk')
    )
    # server_default so this doesn't fail if 'artifact' already has rows (autogenerate
    # doesn't know that ix_chunk_bm25_tsv/ix_chunk_embedding_cosine below were created
    # via raw op.execute() in 0001, not a SQLAlchemy Index() it can track — dropping
    # them here would be wrong, so those two autogenerated drop_index calls are removed).
    op.add_column('artifact', sa.Column('requirement_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('artifact', sa.Column('stale', sa.Boolean(), nullable=False, server_default=sa.false()))

    # P1 for test_plan, same DEFERRABLE pattern as requirement/source_citation in 0001.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION check_test_plan_has_citation() RETURNS trigger AS $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM test_plan_citation WHERE test_plan_id = NEW.id) THEN
                RAISE EXCEPTION 'P1 violation: test_plan % has no TestPlanCitation', NEW.id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER trg_test_plan_has_citation
        AFTER INSERT ON test_plan
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION check_test_plan_has_citation()
        """
    )
    # ### end Alembic commands ###


# Function: downgrade
def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_test_plan_has_citation ON test_plan")
    op.execute("DROP FUNCTION IF EXISTS check_test_plan_has_citation")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact', 'stale')
    op.drop_column('artifact', 'requirement_ids')
    op.drop_table('test_plan_citation')
    op.drop_table('test_plan')
    op.drop_table('connector_config')
    # ### end Alembic commands ###
