# ---------------------------------------------------------------------------
# Author: Vishnuu A
# Scope: TraceForge — api/alembic/versions (ff812f04885c_initial.py)
# Date: 2026-06-06
# ---------------------------------------------------------------------------
"""initial

Revision ID: ff812f04885c
Revises: 
Create Date: 2026-07-11 21:37:56.917494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = 'ff812f04885c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Function: upgrade
def upgrade() -> None:
    # pgvector must exist before any table declares a VECTOR column (chunk.embedding below).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: project.brd_template_id -> template.id and template.project_id -> project.id
    # form a genuine circular FK. Create 'project' WITHOUT the brd_template_id FK first,
    # create 'template', then add the FK via ALTER TABLE once both tables exist.
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('brd_template_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')", name='ck_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('blob_uri', sa.String(length=1024), nullable=False),
    sa.Column('section_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("kind IN ('BRD', 'FRD', 'RTM', 'TEST_CASE')", name='ck_kind'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_project_brd_template_id', 'project', 'template', ['brd_template_id'], ['id'])
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('id_sequence',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'prefix')
    )
    op.create_table('pipeline_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('INGEST', 'EXTRACT', 'BRD', 'TEST_DESIGN', 'SCRIPT_GEN', 'RENDER')", name='ck_stage'),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'AWAITING_APPROVAL', 'APPROVED', 'REJECTED', 'FAILED')", name='ck_status'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('req_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_req_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('ears_pattern', sa.String(length=64), nullable=False),
    sa.Column('ears_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.String(length=64), nullable=False),
    sa.Column('ambiguity_score', sa.Float(), nullable=False),
    sa.Column('ambiguity_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_agent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ears_pattern IN ('UBIQUITOUS', 'EVENT_DRIVEN', 'STATE_DRIVEN', 'OPTIONAL_FEATURE', 'UNWANTED_BEHAVIOUR', 'COMPLEX', 'NON_CONFORMANT')", name='ck_ears_pattern'),
    sa.CheckConstraint("level IN ('BUSINESS', 'FUNCTIONAL', 'NON_FUNCTIONAL', 'CONSTRAINT', 'ASSUMPTION')", name='ck_level'),
    sa.CheckConstraint("priority IN ('MUST', 'SHOULD', 'COULD', 'WONT')", name='ck_priority'),
    sa.CheckConstraint("status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED', 'SUSPECT')", name='ck_status'),
    sa.ForeignKeyConstraint(['parent_req_id'], ['requirement.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'req_id', name='uq_requirement_project_req_id')
    )
    op.create_table('servicenow_incident',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_incident_project_number')
    )
    op.create_table('source_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('connector_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('blob_uri', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('doc_class', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("doc_class IN ('AS_IS_DOC', 'SOW', 'PROCESS_MAP', 'INCIDENT_DATA', 'LEGACY_CODE', 'KB_ARTICLE', 'OTHER')", name='ck_doc_class'),
    sa.CheckConstraint("source_type IN ('SERVICENOW', 'UPLOAD', 'GIT_REPO', 'URL')", name='ck_source_type'),
    sa.CheckConstraint("status IN ('PENDING', 'PARSING', 'INDEXED', 'FAILED')", name='ck_status'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('blob_uri', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('BRD_DOCX', 'FRD_DOCX', 'RTM_XLSX', 'TEST_PACK_ZIP', 'SCRIPT_BUNDLE_ZIP')", name='ck_kind'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('bm25_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'ordinal', name='uq_chunk_source_ordinal')
    )
    op.create_table('gate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('required_role', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('item_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.CheckConstraint("decision IN ('PENDING', 'APPROVED', 'REJECTED', 'APPROVED_WITH_COMMENTS')", name='ck_decision'),
    sa.CheckConstraint("required_role IN ('BUSINESS_ANALYST', 'TEST_LEAD', 'ARCHITECT', 'CLIENT_REVIEWER')", name='ck_required_role'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_call',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tc_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('test_type', sa.String(length=64), nullable=False),
    sa.Column('test_level', sa.String(length=64), nullable=False),
    sa.Column('preconditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gherkin', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('upstream_req_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_agent', sa.Boolean(), nullable=False),
    sa.CheckConstraint("priority IN ('P1','P2','P3')", name='ck_test_case_priority'),
    sa.CheckConstraint("status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'SUSPECT')", name='ck_status'),
    sa.CheckConstraint("test_level IN ('UNIT', 'API', 'UI_E2E', 'INTEGRATION', 'UAT')", name='ck_test_level'),
    sa.CheckConstraint("test_type IN ('POSITIVE', 'NEGATIVE', 'EDGE', 'BOUNDARY', 'NEGATIVE_SECURITY', 'PERFORMANCE')", name='ck_test_type'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tc_id', name='uq_testcase_project_tc_id')
    )
    op.create_table('source_citation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('quoted_span', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'chunk_id', name='uq_citation_req_chunk')
    )
    op.create_table('test_script',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('page_objects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compiles', sa.Boolean(), nullable=True),
    sa.Column('validation_output', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('upstream_tc_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'SUSPECT')", name='ck_status'),
    sa.CheckConstraint("target IN ('PLAYWRIGHT_TS', 'PYTEST', 'KARATE', 'TOSCA_XML', 'ROBOT')", name='ck_target'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ts_id', name='uq_testscript_project_ts_id')
    )
    # ### end Alembic commands ###

    # ── Hand-written additions below: indexes + P1/P7 enforcement (spec §3, §6.2, §7) ──

    # Hybrid retrieval support indexes (§4.3): cosine ANN on the embedding, GIN on the
    # generated tsvector, for the RRF fusion a later phase will implement.
    op.execute("CREATE INDEX ix_chunk_embedding_cosine ON chunk USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX ix_chunk_bm25_tsv ON chunk USING gin (bm25_tsv)")

    # P1 — "Every Requirement MUST have >=1 SourceCitation row. DB constraint + API
    # validator rejects otherwise." A plain FK can't express "at least one row exists
    # in a related table" (the Requirement must be inserted before its citations can
    # reference it), so this is a deferred constraint trigger: it runs at COMMIT time,
    # after both the requirement and its citation rows have been inserted in the same
    # transaction, and rolls the whole transaction back if the requirement still has
    # zero citations. The API also validates this before it ever issues the insert
    # (traceforge/agents/extractor.py) so the common case fails fast with a clean
    # error; this trigger is the backstop for anything that bypasses the API.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION check_requirement_has_citation() RETURNS trigger AS $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM source_citation WHERE requirement_id = NEW.id) THEN
                RAISE EXCEPTION 'P1 violation: requirement % has no SourceCitation', NEW.req_id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER trg_requirement_has_citation
        AFTER INSERT ON requirement
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION check_requirement_has_citation()
        """
    )

    # P7 — "Every state transition ... writes an immutable AuditEvent." Enforced as a
    # trigger (not a GRANT) so it holds regardless of which DB role the app connects
    # as; RBAC-scoped roles are Phase 4 (see PROGRESS.md).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_audit_event_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_event is append-only: % not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_event_immutable
        BEFORE UPDATE OR DELETE ON audit_event
        FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation()
        """
    )


# Function: downgrade
def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_event_immutable ON audit_event")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_event_mutation")
    op.execute("DROP TRIGGER IF EXISTS trg_requirement_has_citation ON requirement")
    op.execute("DROP FUNCTION IF EXISTS check_requirement_has_citation")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_script')
    op.drop_table('source_citation')
    op.drop_table('test_case')
    op.drop_table('llm_call')
    op.drop_table('gate')
    op.drop_table('chunk')
    op.drop_table('artifact')
    op.drop_table('source_document')
    op.drop_table('servicenow_incident')
    op.drop_table('requirement')
    op.drop_table('pipeline_run')
    op.drop_table('id_sequence')
    op.drop_table('audit_event')
    op.drop_table('template')
    op.drop_table('project')
    # ### end Alembic commands ###
