# ---------------------------------------------------------------------------
# Author: Vishnuu A
# Scope: Small runtime libraries embedded into deterministic generated test scripts.
# Date: 2026-02-03
# ---------------------------------------------------------------------------
"""Small runtime libraries embedded into deterministic generated test scripts."""

# Marker comments used to locate the inline runtime block inside generated spec files
# so the ZIP bundler can replace it with a shared-module import.
RUNTIME_REGION_START = "// BEGIN_TRACEFORGE_RUNTIME"
RUNTIME_REGION_END = "// END_TRACEFORGE_RUNTIME"

PLAYWRIGHT_RUNTIME = r'''type ReviewedStep = { action: string; expected: string; data: unknown; scenario?: string };
declare const process: { env: Record<string, string | undefined> };

/**
 * TRACEFORGE AUTOMATION READINESS NOTICE
 *
 * This test file was generated by TraceForge. Before attempting execution:
 *
 * 1. Set PLAYWRIGHT_BASE_URL to the real application URL.
 * 2. Supply TRACEFORGE_LOCATORS as a JSON map of business field names to stable selectors.
 *    Example: {"Product Code Field": "[data-testid=product-code]", "Order Submit Button": "[data-testid=submit-order]"}
 * 3. Implement real authentication (storage state, storageState fixture, or loginPage helper).
 * 4. Confirm test-data factory and cleanup process with the business owner.
 * 5. Resolve all [EXECUTION DETAIL BLOCKED] markers in the test steps.
 * 6. Disable fullyParallel for tests sharing FSC balance, stock, invoices, or production orders.
 *
 * Tests with unresolved [EXECUTION DETAIL BLOCKED] markers WILL FAIL. This is by design —
 * the marker means the business owner must supply the missing information before automation is possible.
 */

const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? process.env.TRACEFORGE_BASE_URL ?? 'http://localhost:3000';
const LOCATOR_MAP: Record<string, string> = (() => {
  const raw = process.env.TRACEFORGE_LOCATORS;
  if (!raw) return {};
  try { return JSON.parse(raw) as Record<string, string>; }
  catch { throw new Error('TRACEFORGE_LOCATORS must be a valid JSON object mapping business field names to CSS/testId selectors.'); }
})();

function uniqueTestCorrelationId(): string {
  return process.env.TRACEFORGE_TEST_VALUE
    ?? `tf-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Resolve a locator using the supplied TRACEFORGE_LOCATORS map first (preferred),
 * then fall back to role/label/testId heuristics.
 *
 * IMPORTANT: This fallback will fail when the mapped text does not match any
 * accessible name in the real application. Supply real selectors via TRACEFORGE_LOCATORS.
 */
async function semanticLocator(page: Page, hint: string): Promise<Locator> {
  // Prefer explicitly mapped selectors from the automation context pack
  const mapped = LOCATOR_MAP[hint] ?? LOCATOR_MAP[hint.toLowerCase()];
  if (mapped) {
    const loc = page.locator(mapped);
    await expect(loc, `Configured selector for "${hint}" must match exactly one element`).toHaveCount(1);
    return loc;
  }

  // Fallback: attempt accessible-name heuristics (unreliable without real application metadata)
  const namePattern = new RegExp(hint.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
  const candidates: Locator[] = [
    page.getByTestId(hint),
    page.getByRole('button', { name: namePattern }),
    page.getByRole('link', { name: namePattern }),
    page.getByLabel(namePattern),
    page.getByPlaceholder(namePattern),
  ];
  for (const c of candidates) {
    if (await c.count() === 1) return c;
  }

  // Fail with actionable guidance rather than a cryptic locator error
  throw new Error(
    `AUTOMATION BLOCKED: No unique element matched "${hint}".\n` +
    `Add a real selector to TRACEFORGE_LOCATORS, e.g.:\n` +
    `  TRACEFORGE_LOCATORS='{"${hint}": "[data-testid=your-real-id]"}'\n` +
    `Or update the test step to use getByTestId/getByRole with the actual application element.`
  );
}

async function assertBusinessState(page: Page, expected: string): Promise<void> {
  await expect(page.locator('body')).toBeVisible();
  // Only assert specific business-state text when it is a concrete value (not a generic sentence)
  const trimmed = expected.trim();
  const isConcreteAssertion = trimmed.length >= 8
    && !/^(the (system|application|process)|verify|confirm|check|observe|ensure)\b/i.test(trimmed)
    && !/\[EXECUTION DETAIL BLOCKED\]/.test(trimmed);
  if (isConcreteAssertion) {
    const fragment = trimmed.split(/[.;]/)[0].trim().slice(0, 80);
    if (fragment.length >= 6) {
      await expect(page.locator('body'), `Expected business state: ${expected}`).toContainText(
        new RegExp(fragment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'),
      );
    }
  }
}

async function executeReviewedStep(page: Page, step: ReviewedStep): Promise<void> {
  const action = step.action.trim();
  const data = typeof step.data === 'string' ? step.data : JSON.stringify(step.data ?? '');

  // Surface blocked steps as explicit test failures with guidance
  if (/\[EXECUTION DETAIL BLOCKED\]/.test(action)) {
    throw new Error(
      `AUTOMATION BLOCKED — this step cannot be automated until the business owner supplies the missing information:\n${action}`
    );
  }

  // Navigate to the application if not already there
  if (/\b(open the application|navigate to the application|go to)\b/i.test(action) && page.url() === 'about:blank') {
    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded' });
    await expect(page.locator('body')).toBeVisible();
    await assertBusinessState(page, step.expected);
    return;
  }

  // Derive the target hint from the step action
  const hintMatch = action.match(/\b(?:click|press|select|enter|fill|navigate to|open)\s+(?:the\s+)?["'[]?([A-Z][^"'\]]{4,60})["'\]]/i)
    ?? action.match(/\b(?:the|in|on)\s+["']?([A-Z][a-zA-Z ]{4,50})["']?\s+(?:field|button|screen|page|tab|link)/i);
  const hint = hintMatch?.[1]?.trim() ?? action.slice(0, 60);

  const suppliedData = data && !/^(use|capture|reuse|pending|tbd|n\/a)/i.test(data)
    ? data : uniqueTestCorrelationId();

  const target = await semanticLocator(page, hint);

  if (/\b(enter|type|input|provide|fill|populate)\b/i.test(action)) {
    await expect(target).toBeEditable();
    await target.fill(suppliedData);
  } else if (/\b(select|choose)\b/i.test(action)) {
    const tag = await target.evaluate((el: Element) => el.tagName.toLowerCase());
    if (tag === 'select') {
      await target.selectOption({ label: suppliedData });
    } else {
      await target.click();
    }
  } else {
    await expect(target).toBeEnabled();
    await target.click();
  }

  await assertBusinessState(page, step.expected);
}
'''

# Exportable version placed in tests/helpers/traceforge-runtime.ts inside the ZIP bundle.
# Spec files import from this instead of duplicating the runtime 84 times.
PLAYWRIGHT_RUNTIME_MODULE = '''\
/**
 * TraceForge shared automation runtime helpers.
 * Generated by TraceForge — placed in tests/helpers/traceforge-runtime.ts.
 *
 * SETUP REQUIRED before executing tests:
 * 1. Set PLAYWRIGHT_BASE_URL to the real application URL.
 * 2. Populate TRACEFORGE_LOCATORS with a JSON map of business field names to stable selectors:
 *    Example: {"Product Code Field": "[data-testid=product-code]"}
 * 3. Implement authentication in tests/fixtures/auth.fixture.ts (storage state or login page).
 * 4. Confirm test-data factory and cleanup process with the business owner.
 * 5. Resolve every [EXECUTION DETAIL BLOCKED] marker before attempting execution.
 * 6. Do NOT enable fullyParallel for tests that share FSC balances, stock, invoices, or production orders.
 */
import { expect, type Locator, type Page } from \'@playwright/test\';

export const BASE_URL: string = process.env.PLAYWRIGHT_BASE_URL
  ?? process.env.TRACEFORGE_BASE_URL
  ?? \'http://localhost:3000\';

const LOCATOR_MAP: Record<string, string> = (() => {
  const raw = process.env.TRACEFORGE_LOCATORS;
  if (!raw) return {};
  try { return JSON.parse(raw) as Record<string, string>; }
  catch { throw new Error(\'TRACEFORGE_LOCATORS must be a valid JSON object mapping business field names to CSS/testId selectors.\'); }
})();

export function uniqueTestCorrelationId(): string {
  return process.env.TRACEFORGE_TEST_VALUE
    ?? `tf-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Resolve a locator from TRACEFORGE_LOCATORS first (preferred — supply real selectors here),
 * then fall back to accessible-name heuristics.
 * When no real selector is mapped, tests WILL fail with an actionable error message.
 */
export async function semanticLocator(page: Page, hint: string): Promise<Locator> {
  const mapped = LOCATOR_MAP[hint] ?? LOCATOR_MAP[hint.toLowerCase()];
  if (mapped) {
    const loc = page.locator(mapped);
    await expect(loc, `Configured selector for "${hint}" must match exactly one element`).toHaveCount(1);
    return loc;
  }
  const namePattern = new RegExp(hint.replace(/[.*+?^${}()|[\\]\\\\]/g, \'\\\\$&\'), \'i\');
  const candidates: Locator[] = [
    page.getByTestId(hint),
    page.getByRole(\'button\', { name: namePattern }),
    page.getByRole(\'link\', { name: namePattern }),
    page.getByLabel(namePattern),
    page.getByPlaceholder(namePattern),
  ];
  for (const c of candidates) { if (await c.count() === 1) return c; }
  throw new Error(
    `AUTOMATION BLOCKED: No unique element matched "${hint}".\\n` +
    `Map the real selector in TRACEFORGE_LOCATORS, e.g.:\\n` +
    `  TRACEFORGE_LOCATORS=\'{"${hint}": "[data-testid=your-real-id]"}\\'`
  );
}

export async function assertBusinessState(page: Page, expected: string): Promise<void> {
  await expect(page.locator(\'body\')).toBeVisible();
  const trimmed = expected.trim();
  const isConcreteAssertion = trimmed.length >= 8
    && !/^(the (system|application|process)|verify|confirm|check|observe|ensure)\\b/i.test(trimmed)
    && !/\\[EXECUTION DETAIL BLOCKED\\]/.test(trimmed);
  if (isConcreteAssertion) {
    const fragment = trimmed.split(/[.;]/)[0].trim().slice(0, 80);
    if (fragment.length >= 6) {
      await expect(page.locator(\'body\'), `Expected: ${expected}`).toContainText(
        new RegExp(fragment.replace(/[.*+?^${}()|[\\]\\\\]/g, \'\\\\$&\'), \'i\'),
      );
    }
  }
}

export async function executeReviewedStep(page: Page, step: { action: string; expected: string; data: unknown; scenario?: string }): Promise<void> {
  const action = step.action.trim();
  const data = typeof step.data === \'string\' ? step.data : JSON.stringify(step.data ?? \'\');

  if (/\\[EXECUTION DETAIL BLOCKED\\]/.test(action)) {
    throw new Error(`AUTOMATION BLOCKED — supply missing information to the business owner:\\n${action}`);
  }
  if (/\\b(open the application|navigate to the application|go to)\\b/i.test(action) && page.url() === \'about:blank\') {
    await page.goto(BASE_URL, { waitUntil: \'domcontentloaded\' });
    await expect(page.locator(\'body\')).toBeVisible();
    await assertBusinessState(page, step.expected);
    return;
  }
  const hintMatch = action.match(/\\b(?:click|press|select|enter|fill|navigate to|open)\\s+(?:the\\s+)?["\'[]?([A-Z][^"\\'\\]]{4,60})["\'\\]]/i)
    ?? action.match(/\\b(?:the|in|on)\\s+["\\']?([A-Z][a-zA-Z ]{4,50})["\\']?\\s+(?:field|button|screen|page|tab|link)/i);
  const hint = hintMatch?.[1]?.trim() ?? action.slice(0, 60);
  const suppliedData = data && !/^(use|capture|reuse|pending|tbd|n\\/a)/i.test(data) ? data : uniqueTestCorrelationId();
  const target = await semanticLocator(page, hint);
  if (/\\b(enter|type|input|provide|fill|populate)\\b/i.test(action)) {
    await expect(target).toBeEditable(); await target.fill(suppliedData);
  } else if (/\\b(select|choose)\\b/i.test(action)) {
    const tag = await target.evaluate((el: Element) => el.tagName.toLowerCase());
    if (tag === \'select\') { await target.selectOption({ label: suppliedData }); } else { await target.click(); }
  } else { await expect(target).toBeEnabled(); await target.click(); }
  await assertBusinessState(page, step.expected);
}
'''


SELENIUM_RUNTIME = r'''type ReviewedStep = { action: string; expected: string; data: unknown; scenario?: string };
declare const process: { env: Record<string, string | undefined> };

const BASE_URL = process.env.TRACEFORGE_BASE_URL ?? 'http://localhost:3000';
const TEST_VALUE = process.env.TRACEFORGE_TEST_VALUE ?? 'TraceForge-Test-Value';

function meaningfulText(value: string, fallback: string): string {
  const cleaned = value
    .replace(/^(prepare|attempt|verify|the system shall|the application shall|customers? shall)\s*/i, '')
    .replace(/\b(the|a|an|shall|should|be able to|documented|approved|requirement|scenario)\b/gi, ' ')
    .replace(/[^a-z0-9 ]/gi, ' ').replace(/\s+/g, ' ').trim();
  return (cleaned || fallback).split(' ').slice(0, 8).join(' ');
}

function xpathLiteral(value: string): string {
  if (!value.includes("'")) return `'${value}'`;
  if (!value.includes('"')) return `"${value}"`;
  return `concat('${value.replace(/'/g, `', "'", '`)}')`;
}

async function semanticElement(driver: WebDriver, hint: string): Promise<WebElement> {
  const literal = xpathLiteral(hint.toLowerCase());
  const xpath = `//*[self::button or self::a or self::input or self::select or self::textarea or @role='button' or @role='link'][contains(translate(concat(normalize-space(.), ' ', @aria-label, ' ', @placeholder, ' ', @name), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), ${literal})]`;
  const matches = await driver.findElements(By.xpath(xpath));
  if (matches.length) return matches[0];
  throw new Error(`No accessible control matched "${hint}". Set TRACEFORGE_BASE_URL and expose a matching accessible name or label.`);
}

async function executeReviewedStep(driver: WebDriver, step: ReviewedStep): Promise<void> {
  const action = step.action.trim();
  const scenario = typeof step.scenario === 'string' && step.scenario.trim() ? step.scenario : action;
  const data = typeof step.data === 'string' ? step.data : JSON.stringify(step.data ?? '');
  if (/^prepare\b/i.test(action)) {
    await driver.get(BASE_URL);
    assert.ok((await driver.findElements(By.css('body'))).length === 1, 'Application body is available');
    return;
  }

  const hint = meaningfulText(action, scenario);
  let target: WebElement;
  try { target = await semanticElement(driver, hint); }
  catch { target = await semanticElement(driver, meaningfulText(scenario, scenario)); }
  if (/\b(enter|type|input|provide|update|create)\b/i.test(action)) {
    await target.clear();
    await target.sendKeys(data && !/^use\b/i.test(data) ? data : TEST_VALUE);
  } else {
    await target.click();
  }

  const bodyText = await driver.findElement(By.css('body')).getText();
  assert.ok(bodyText.trim().length > 0, step.expected || 'Application returned visible content');
}
'''
