// ---------------------------------------------------------------------------
// Author: Vishnuu A
// Scope: TraceForge — ui/src/components (CitationDrawer.tsx)
// Date: 2025-09-11
// ---------------------------------------------------------------------------
import { useQuery } from '@tanstack/react-query'
import { X } from 'lucide-react'
import api from '../api/client'
import type { RequirementDetail } from '../api/types'

// Function: CitationDrawer
export default function CitationDrawer({ requirementId, onClose }: { requirementId: string; onClose: () => void }) {
  const { data } = useQuery<RequirementDetail>({
    queryKey: ['requirement', requirementId],
    queryFn: async () => (await api.get(`/requirements/${requirementId}`)).data,
  })

  return (
    <div className="w-96 shrink-0 border-l border-white/10 bg-gray-950 overflow-y-auto">
      <div className="p-4 border-b border-white/10 flex items-center justify-between sticky top-0 bg-gray-950">
        <div>
          <p className="text-xs text-gray-500">{data?.req_id}</p>
          <h3 className="text-sm font-semibold text-white">Citations</h3>
        </div>
        <button onClick={onClose} className="text-gray-500 hover:text-white"><X size={16} /></button>
      </div>

      {!data ? (
        <p className="p-4 text-xs text-gray-600">Loading…</p>
      ) : (
        <div className="p-4 space-y-3">
          {data.citations.length === 0 && (
            <p className="text-xs text-red-400">No citations — this should be impossible for an agent-generated requirement (P1). If you're seeing this, it was hand-added without a source.</p>
          )}
          {data.citations.map((citation) => (
            <div key={citation.id} className="bg-gray-900 border border-white/10 rounded-lg p-3">
              <p className="text-[11px] text-blue-300 font-medium">{citation.source_document_filename}</p>
              <p className="text-[10px] text-gray-500 mt-0.5">
                {String((citation.locator as any)?.section || '')}
                {(citation.locator as any)?.char_start != null && ` · chars ${(citation.locator as any).char_start}-${(citation.locator as any).char_end}`}
              </p>
              <blockquote className="mt-2 text-xs text-gray-300 border-l-2 border-blue-500/50 pl-2 italic">
                "{citation.quoted_span}"
              </blockquote>
            </div>
          ))}

          <div className="pt-3 border-t border-white/10">
            <p className="text-[10px] text-gray-500 uppercase tracking-wide mb-1">Provenance</p>
            <p className="text-xs text-gray-400">
              {data.created_by_agent ? 'Generated by Agent 1 (Requirement Extractor)' : 'Hand-edited by a reviewer'} · v{data.version}
            </p>
          </div>

          {data.ambiguity_flags.length > 0 && (
            <div className="pt-3 border-t border-white/10 space-y-2">
              <p className="text-[10px] text-gray-500 uppercase tracking-wide">Ambiguity flags</p>
              {data.ambiguity_flags.map((flag, i) => (
                <div key={i} className="bg-amber-500/5 border border-amber-500/20 rounded p-2">
                  <p className="text-[11px] text-amber-300 font-medium">{flag.code}</p>
                  <p className="text-[11px] text-gray-400 mt-0.5">{flag.explanation}</p>
                  <p className="text-[11px] text-gray-500 mt-0.5">→ {flag.suggestion}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
