apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: createafullstacksolutionforabank
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: createafullstacksolutionforabank
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
