server {
  listen 80;
  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }
  location /api/kg/ {
    proxy_pass http://kg-service:8001/;
  }
  location /api/inspector/ {
    proxy_pass http://signal-inspector:8003/;
  }
  location /api/agents/ {
    proxy_pass http://agent-service:8002/;
  }
}
