dao.config.root.dir=/xml/dao/
dao.factory.config.file=/xml/k4DAO.xml
#dao.schema.registry.file=/xml/dao/SchemaRegistry.xml
dao.schema.registry.locator.impl=com.mazdausa.corporate.vehicles.distribution.application.util.SchemaRegistryLocatorImpl
