# ---------------------------------------------------------------------------
# Author: Vishnuu A
# Scope: Lets a project's pipeline be re-run from a clean slate after a failed/stuck stage,
# Date: 2026-04-23
# ---------------------------------------------------------------------------
"""Lets a project's pipeline be re-run from a clean slate after a failed/stuck stage,
without touching anything the pipeline actually produced."""
from __future__ import annotations

import uuid
import shutil

from sqlalchemy import delete, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from traceforge.config import STORAGE_DIR
from traceforge.db.models import (
    Artifact, AuditEvent, Chunk, ConnectorConfig, Gate, IdSequence, LLMCall,
    PipelineRun, Requirement, ServiceNowIncident, SourceCitation, SourceDocument,
    TestCase, TestPlan, TestPlanCitation, TestScript,
)


# Function: reset_pipeline
async def reset_pipeline(session: AsyncSession, project_id: uuid.UUID, actor: str) -> int:
    """Wipes this project's PipelineRun/Gate/LLMCall history so every stage shows
    'idle' again, as if the project were freshly created. Does NOT touch anything the
    pipeline actually produced — Requirement/TestCase/TestScript/TestPlan/Artifact rows
    and their approval statuses are left exactly as they are; Artifact/TestPlan just
    have their now-dangling pipeline_run_id nulled out (both columns are nullable for
    exactly this reason) since the run they were generated by no longer exists.

    Returns the number of PipelineRun rows deleted."""
    run_ids = list((await session.execute(
        select(PipelineRun.id).where(PipelineRun.project_id == project_id)
    )).scalars().all())
    run_ids_subq = select(PipelineRun.id).where(PipelineRun.project_id == project_id).scalar_subquery()

    await session.execute(update(Artifact).where(Artifact.pipeline_run_id.in_(run_ids_subq)).values(pipeline_run_id=None))
    await session.execute(update(TestPlan).where(TestPlan.pipeline_run_id.in_(run_ids_subq)).values(pipeline_run_id=None))
    await session.execute(delete(LLMCall).where(LLMCall.pipeline_run_id.in_(run_ids_subq)))
    await session.execute(delete(Gate).where(Gate.pipeline_run_id.in_(run_ids_subq)))
    await session.execute(delete(PipelineRun).where(PipelineRun.project_id == project_id))

    session.add(AuditEvent(
        project_id=project_id, actor=actor, action="PIPELINE_RESET",
        entity_type="Project", entity_id=str(project_id), before={"runs_deleted": len(run_ids)}, after=None,
    ))
    return len(run_ids)


# Function: clear_project_data
async def clear_project_data(session: AsyncSession, project_id: uuid.UUID, actor: str) -> dict[str, int]:
    """Delete every source and generated pipeline record while retaining the Project,
    its configuration/templates, and its immutable AuditEvent history."""
    counts = {
        "sources": len(list((await session.scalars(select(SourceDocument.id).where(SourceDocument.project_id == project_id))).all())),
        "requirements": len(list((await session.scalars(select(Requirement.id).where(Requirement.project_id == project_id))).all())),
        "test_cases": len(list((await session.scalars(select(TestCase.id).where(TestCase.project_id == project_id))).all())),
        "scripts": len(list((await session.scalars(select(TestScript.id).where(TestScript.project_id == project_id))).all())),
        "artifacts": len(list((await session.scalars(select(Artifact.id).where(Artifact.project_id == project_id))).all())),
        "runs": len(list((await session.scalars(select(PipelineRun.id).where(PipelineRun.project_id == project_id))).all())),
    }

    run_ids = select(PipelineRun.id).where(PipelineRun.project_id == project_id)
    requirement_ids = select(Requirement.id).where(Requirement.project_id == project_id)
    plan_ids = select(TestPlan.id).where(TestPlan.project_id == project_id)

    # Delete from the leaves toward their project-owned parents to satisfy FKs.
    await session.execute(delete(TestPlanCitation).where(TestPlanCitation.test_plan_id.in_(plan_ids)))
    await session.execute(delete(SourceCitation).where(SourceCitation.requirement_id.in_(requirement_ids)))
    await session.execute(delete(TestScript).where(TestScript.project_id == project_id))
    await session.execute(delete(TestCase).where(TestCase.project_id == project_id))
    await session.execute(delete(TestPlan).where(TestPlan.project_id == project_id))
    await session.execute(delete(Artifact).where(Artifact.project_id == project_id))
    await session.execute(delete(Requirement).where(Requirement.project_id == project_id))
    await session.execute(delete(LLMCall).where(LLMCall.pipeline_run_id.in_(run_ids)))
    await session.execute(delete(Gate).where(Gate.pipeline_run_id.in_(run_ids)))
    await session.execute(delete(PipelineRun).where(PipelineRun.project_id == project_id))
    await session.execute(delete(ServiceNowIncident).where(ServiceNowIncident.project_id == project_id))
    await session.execute(delete(Chunk).where(Chunk.project_id == project_id))
    await session.execute(delete(SourceDocument).where(SourceDocument.project_id == project_id))
    await session.execute(delete(IdSequence).where(IdSequence.project_id == project_id))
    await session.execute(delete(ConnectorConfig).where(ConnectorConfig.project_id == project_id))

    session.add(AuditEvent(
        project_id=project_id, actor=actor, action="PROJECT_STARTED_FRESH",
        entity_type="Project", entity_id=str(project_id), before=counts,
        after={"sources": 0, "requirements": 0, "test_cases": 0, "scripts": 0, "artifacts": 0, "runs": 0},
    ))
    return counts


# Function: clear_project_storage
def clear_project_storage(project_id: uuid.UUID) -> bool:
    project_dir = STORAGE_DIR / str(project_id)
    if not project_dir.exists():
        return False
    shutil.rmtree(project_dir)
    return True
