# ---------------------------------------------------------------------------
# Author: Vishnuu A
# Scope: services/iac_generator.py
# Date: 2026-04-30
# ---------------------------------------------------------------------------
"""
services/iac_generator.py
Infrastructure-as-Code STARTER TEMPLATE generation (Terraform / Azure ARM /
AWS CloudFormation) from a scan report's server inventory.

Deliberately output-only: these are scaffolds a migration engineer edits and
applies themselves (subscription IDs, VPC/VNet/subnet IDs, credentials, and
naming conventions are all left as variables/placeholders) — this module
never calls a cloud provider's API and never provisions anything. Actually
creating real cloud resources needs real account credentials and a real
target network topology this tool has no way to know; generating a correct,
reviewable starting point is the honest and useful scope for "IaC output."

Only servers with is_iac_candidate()==True are included — network appliances,
0-CPU/0-RAM entries (routers, firewalls, printers picked up by discovery),
and anything already marked for decommission are excluded, since there is
nothing meaningful to provision for them.
"""
from __future__ import annotations

import json
import re
from typing import Any, Optional

_VM_SIZE_BY_PROVIDER = {
    "azure": {
        (2, 4): "Standard_B2als_v2", (2, 8): "Standard_D2s_v3", (4, 16): "Standard_D4s_v3",
        (8, 32): "Standard_D8s_v3", (16, 64): "Standard_D16s_v3", (32, 128): "Standard_D32s_v3",
    },
    "aws": {
        (2, 4): "t3.medium", (2, 8): "m5.large", (4, 16): "m5.xlarge",
        (8, 32): "m5.2xlarge", (16, 64): "m5.4xlarge", (32, 128): "m5.8xlarge",
    },
    "gcp": {
        (2, 4): "e2-medium", (2, 8): "e2-standard-2", (4, 16): "e2-standard-4",
        (8, 32): "e2-standard-8", (16, 64): "e2-standard-16", (32, 128): "n2-standard-32",
    },
}


# Function: _closest_size
def _closest_size(provider: str, cpu: int, ram: float) -> str:
    """Nearest catalog entry that covers the server's cpu/ram, largest fallback if none fit."""
    catalog = _VM_SIZE_BY_PROVIDER.get(provider, _VM_SIZE_BY_PROVIDER["azure"])
    candidates = [(c, r) for (c, r) in catalog if c >= cpu and r >= ram]
    key = min(candidates, key=lambda cr: (cr[0] - cpu) + (cr[1] - ram)) if candidates else max(catalog.keys())
    return catalog[key]


# Function: _sanitize_name
def _sanitize_name(name: str) -> str:
    """Resource-name-safe identifier: lowercase, alphanumeric + hyphen only."""
    cleaned = re.sub(r"[^a-zA-Z0-9-]", "-", name or "server").strip("-").lower()
    return cleaned or "server"


# Function: is_iac_candidate
def is_iac_candidate(server: dict) -> bool:
    cpu = server.get("cpu_cores") or 0
    ram = server.get("ram_gb") or server.get("memory_gb") or 0
    if cpu <= 0 or ram <= 0:
        return False
    if (server.get("migration_strategy") or "").lower() == "decommission":
        return False
    return True


# Function: _select_servers
def _select_servers(report: dict, server_names: Optional[list[str]] = None) -> list[dict]:
    servers = report.get("servers") or []
    candidates = [s for s in servers if is_iac_candidate(s)]
    if server_names:
        wanted = set(server_names)
        candidates = [s for s in candidates if (s.get("server_name") or s.get("name")) in wanted]
    return candidates


# ─── Terraform ────────────────────────────────────────────────────────────────

_TF_HEADER = """# Generated by StratIQ InfraRationalization — Terraform starter template
# Source scan: {scan_name} ({server_count} server(s))
# Target provider: {provider}
#
# This is a STARTING POINT, not a ready-to-apply configuration:
#   - Fill in the placeholder variables below (resource group / VPC / subnet /
#     region) for your actual target environment before running `terraform plan`.
#   - Review instance sizing against the TCO & right-sizing analysis for this
#     scan — sizes here are a first-pass mapping from each server's discovered
#     CPU/RAM, not a substitute for that analysis.
#   - No credentials or provider auth are included; configure your provider
#     block per your organization's standard (env vars, OIDC, etc.).
"""


# Function: generate_terraform
def generate_terraform(report: dict, provider: str = "azure", server_names: Optional[list[str]] = None) -> str:
    provider = provider.lower()
    servers = _select_servers(report, server_names)
    scan_name = report.get("report_name") or report.get("scan_id") or "scan"

    blocks = [_TF_HEADER.format(scan_name=scan_name, server_count=len(servers), provider=provider)]

    if provider == "azure":
        blocks.append(_tf_azure_provider_block())
        for s in servers:
            blocks.append(_tf_azure_vm_block(s))
    elif provider == "aws":
        blocks.append(_tf_aws_provider_block())
        for s in servers:
            blocks.append(_tf_aws_instance_block(s))
    elif provider == "gcp":
        blocks.append(_tf_gcp_provider_block())
        for s in servers:
            blocks.append(_tf_gcp_instance_block(s))
    elif provider == "oci":
        blocks.append(_tf_oci_provider_block())
        for s in servers:
            blocks.append(_tf_oci_instance_block(s))
    else:
        raise ValueError(f"Unsupported provider: {provider}")

    return "\n\n".join(blocks) + "\n"


# Function: _tf_azure_provider_block
def _tf_azure_provider_block() -> str:
    return """provider "azurerm" {
  features {}
}

variable "resource_group_name" {
  description = "Target Azure resource group — REPLACE with your actual resource group"
  type        = string
  default     = "REPLACE-ME-resource-group"
}

variable "location" {
  description = "Target Azure region"
  type        = string
  default     = "eastus"
}

variable "subnet_id" {
  description = "Target subnet resource ID — REPLACE with your actual subnet"
  type        = string
  default     = "REPLACE-ME-subnet-id"
}"""


# Function: _tf_azure_vm_block
def _tf_azure_vm_block(server: dict) -> str:
    name = _sanitize_name(server.get("server_name") or server.get("name") or "server")
    cpu = int(server.get("cpu_cores") or 2)
    ram = float(server.get("ram_gb") or server.get("memory_gb") or 4)
    size = _closest_size("azure", cpu, ram)
    os_hint = "Linux" if "linux" in (server.get("os_name") or "").lower() or "ubuntu" in (server.get("os_name") or "").lower() or "red hat" in (server.get("os_name") or "").lower() or "rhel" in (server.get("os_name") or "").lower() else ("Windows" if "windows" in (server.get("os_name") or "").lower() else "Linux (assumed — verify OS)")
    return f"""# Source server: {server.get('server_name', 'unknown')}  |  discovered {cpu} vCPU / {ram} GiB RAM  |  OS: {server.get('os_name', 'unknown')} -> {os_hint}
resource "azurerm_network_interface" "{name}_nic" {{
  name                = "{name}-nic"
  location            = var.location
  resource_group_name = var.resource_group_name
  ip_configuration {{
    name                          = "internal"
    subnet_id                     = var.subnet_id
    private_ip_address_allocation = "Dynamic"
  }}
}}

resource "azurerm_linux_virtual_machine" "{name}" {{
  name                = "{name}"
  resource_group_name = var.resource_group_name
  location            = var.location
  size                = "{size}"  # nearest catalog match to {cpu} vCPU / {ram} GiB — verify against TCO right-sizing analysis
  admin_username      = "REPLACE-ME-admin"
  network_interface_ids = [azurerm_network_interface.{name}_nic.id]
  admin_ssh_key {{
    username   = "REPLACE-ME-admin"
    public_key = "REPLACE-ME-ssh-public-key"
  }}
  os_disk {{
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }}
  source_image_reference {{
    publisher = "REPLACE-ME"   # set to match: {server.get('os_name', 'unknown')}
    offer     = "REPLACE-ME"
    sku       = "REPLACE-ME"
    version   = "latest"
  }}
}}"""


# Function: _tf_aws_provider_block
def _tf_aws_provider_block() -> str:
    return """provider "aws" {
  region = var.region
}

variable "region" {
  description = "Target AWS region"
  type        = string
  default     = "us-east-1"
}

variable "subnet_id" {
  description = "Target subnet ID — REPLACE with your actual subnet"
  type        = string
  default     = "REPLACE-ME-subnet-id"
}

variable "vpc_security_group_ids" {
  description = "Target security group ID(s) — REPLACE with your actual security groups"
  type        = list(string)
  default     = ["REPLACE-ME-sg-id"]
}"""


# Function: _tf_aws_instance_block
def _tf_aws_instance_block(server: dict) -> str:
    name = _sanitize_name(server.get("server_name") or server.get("name") or "server")
    cpu = int(server.get("cpu_cores") or 2)
    ram = float(server.get("ram_gb") or server.get("memory_gb") or 4)
    size = _closest_size("aws", cpu, ram)
    return f"""# Source server: {server.get('server_name', 'unknown')}  |  discovered {cpu} vCPU / {ram} GiB RAM  |  OS: {server.get('os_name', 'unknown')}
resource "aws_instance" "{name}" {{
  ami                    = "REPLACE-ME-ami-id"  # select an AMI matching: {server.get('os_name', 'unknown')}
  instance_type          = "{size}"  # nearest catalog match to {cpu} vCPU / {ram} GiB — verify against TCO right-sizing analysis
  subnet_id              = var.subnet_id
  vpc_security_group_ids = var.vpc_security_group_ids
  tags = {{
    Name              = "{name}"
    SourceServer      = "{server.get('server_name', 'unknown')}"
    MigrationStrategy = "{server.get('migration_strategy', 'unspecified')}"
  }}
}}"""


# Function: _tf_gcp_provider_block
def _tf_gcp_provider_block() -> str:
    return """provider "google" {
  project = var.project_id
  region  = var.region
}

variable "project_id" {
  description = "Target GCP project ID — REPLACE with your actual project"
  type        = string
  default     = "REPLACE-ME-project-id"
}

variable "region" {
  type    = string
  default = "us-central1"
}

variable "zone" {
  type    = string
  default = "us-central1-a"
}

variable "subnetwork" {
  description = "Target subnetwork self-link — REPLACE with your actual subnetwork"
  type        = string
  default     = "REPLACE-ME-subnetwork"
}"""


# Function: _tf_gcp_instance_block
def _tf_gcp_instance_block(server: dict) -> str:
    name = _sanitize_name(server.get("server_name") or server.get("name") or "server")
    cpu = int(server.get("cpu_cores") or 2)
    ram = float(server.get("ram_gb") or server.get("memory_gb") or 4)
    size = _closest_size("gcp", cpu, ram)
    return f"""# Source server: {server.get('server_name', 'unknown')}  |  discovered {cpu} vCPU / {ram} GiB RAM  |  OS: {server.get('os_name', 'unknown')}
resource "google_compute_instance" "{name}" {{
  name         = "{name}"
  machine_type = "{size}"  # nearest catalog match to {cpu} vCPU / {ram} GiB — verify against TCO right-sizing analysis
  zone         = var.zone
  boot_disk {{
    initialize_params {{
      image = "REPLACE-ME-image"  # select an image matching: {server.get('os_name', 'unknown')}
      size  = {max(10, int((server.get('total_storage_gb') or 20)))}
    }}
  }}
  network_interface {{
    subnetwork = var.subnetwork
  }}
}}"""


# Function: _tf_oci_provider_block
def _tf_oci_provider_block() -> str:
    return """provider "oci" {
  # Configure via env vars (TF_VAR_*, OCI_CLI_*) or ~/.oci/config per your org's standard
}

variable "compartment_id" {
  description = "Target OCI compartment OCID — REPLACE with your actual compartment"
  type        = string
  default     = "REPLACE-ME-compartment-ocid"
}

variable "subnet_id" {
  description = "Target subnet OCID — REPLACE with your actual subnet"
  type        = string
  default     = "REPLACE-ME-subnet-ocid"
}

variable "availability_domain" {
  type    = string
  default = "REPLACE-ME-ad"
}"""


# Function: _tf_oci_instance_block
def _tf_oci_instance_block(server: dict) -> str:
    name = _sanitize_name(server.get("server_name") or server.get("name") or "server")
    cpu = int(server.get("cpu_cores") or 2)
    ram = float(server.get("ram_gb") or server.get("memory_gb") or 4)
    return f"""# Source server: {server.get('server_name', 'unknown')}  |  discovered {cpu} OCPU (approx) / {ram} GiB RAM  |  OS: {server.get('os_name', 'unknown')}
# OCI bills flexible shapes per-OCPU + per-GB-memory rather than a fixed SKU —
# see the TCO analysis for this scan's OCI cost estimate at this exact sizing.
resource "oci_core_instance" "{name}" {{
  compartment_id      = var.compartment_id
  availability_domain = var.availability_domain
  display_name        = "{name}"
  shape               = "VM.Standard.E5.Flex"
  shape_config {{
    ocpus         = {cpu}
    memory_in_gbs = {ram}
  }}
  create_vnic_details {{
    subnet_id = var.subnet_id
  }}
  source_details {{
    source_type = "image"
    source_id   = "REPLACE-ME-image-ocid"  # select an image matching: {server.get('os_name', 'unknown')}
  }}
}}"""


# ─── Azure ARM Template ───────────────────────────────────────────────────────

# Function: generate_arm_template
def generate_arm_template(report: dict, server_names: Optional[list[str]] = None) -> dict:
    servers = _select_servers(report, server_names)
    resources: list[dict] = []
    for s in servers:
        name = _sanitize_name(s.get("server_name") or s.get("name") or "server")
        cpu = int(s.get("cpu_cores") or 2)
        ram = float(s.get("ram_gb") or s.get("memory_gb") or 4)
        size = _closest_size("azure", cpu, ram)
        resources.append({
            "type": "Microsoft.Compute/virtualMachines",
            "apiVersion": "2023-09-01",
            "name": name,
            "location": "[parameters('location')]",
            "comments": (
                f"Source server: {s.get('server_name', 'unknown')} | "
                f"discovered {cpu} vCPU / {ram} GiB RAM | OS: {s.get('os_name', 'unknown')} | "
                f"size '{size}' is the nearest catalog match — verify against this scan's TCO right-sizing analysis"
            ),
            "properties": {
                "hardwareProfile": {"vmSize": size},
                "osProfile": {
                    "computerName": name,
                    "adminUsername": "REPLACE-ME-admin",
                },
                "storageProfile": {
                    "imageReference": {
                        "publisher": "REPLACE-ME", "offer": "REPLACE-ME", "sku": "REPLACE-ME", "version": "latest",
                    },
                },
                "networkProfile": {
                    "networkInterfaces": [{"id": "[parameters('networkInterfaceId_" + name + "')]"}],
                },
            },
        })

    return {
        "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
        "contentVersion": "1.0.0.0",
        "metadata": {
            "generatedBy": "StratIQ InfraRationalization",
            "sourceScan": report.get("report_name") or report.get("scan_id"),
            "note": (
                "STARTER TEMPLATE — resource group, network interfaces, and image references "
                "are left as parameters/placeholders. Fill these in for your target environment "
                "before deploying; this file is not ready to deploy as-is."
            ),
        },
        "parameters": {
            "location": {"type": "string", "defaultValue": "eastus"},
            **{
                f"networkInterfaceId_{_sanitize_name(s.get('server_name') or s.get('name') or 'server')}": {
                    "type": "string", "defaultValue": "REPLACE-ME-nic-resource-id",
                }
                for s in servers
            },
        },
        "resources": resources,
    }


# ─── AWS CloudFormation ────────────────────────────────────────────────────────

# Function: generate_cloudformation
def generate_cloudformation(report: dict, server_names: Optional[list[str]] = None) -> dict:
    servers = _select_servers(report, server_names)
    resources: dict[str, Any] = {}
    for s in servers:
        name = _sanitize_name(s.get("server_name") or s.get("name") or "server")
        logical_id = "".join(part.capitalize() for part in name.split("-")) or "Server"
        cpu = int(s.get("cpu_cores") or 2)
        ram = float(s.get("ram_gb") or s.get("memory_gb") or 4)
        size = _closest_size("aws", cpu, ram)
        resources[logical_id] = {
            "Type": "AWS::EC2::Instance",
            "Metadata": {
                "SourceServer": s.get("server_name", "unknown"),
                "DiscoveredSpec": f"{cpu} vCPU / {ram} GiB RAM",
                "SourceOS": s.get("os_name", "unknown"),
                "Note": f"'{size}' is the nearest catalog match — verify against this scan's TCO right-sizing analysis",
            },
            "Properties": {
                "InstanceType": size,
                "ImageId": "REPLACE-ME-ami-id",
                "SubnetId": {"Ref": "TargetSubnetId"},
                "SecurityGroupIds": [{"Ref": "TargetSecurityGroupId"}],
                "Tags": [
                    {"Key": "Name", "Value": name},
                    {"Key": "SourceServer", "Value": s.get("server_name", "unknown")},
                    {"Key": "MigrationStrategy", "Value": s.get("migration_strategy", "unspecified")},
                ],
            },
        }

    return {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": (
            f"StratIQ InfraRationalization — starter CloudFormation template from scan "
            f"'{report.get('report_name') or report.get('scan_id')}'. STARTER TEMPLATE, not "
            f"ready to deploy as-is — fill in the placeholder parameters below for your target environment."
        ),
        "Parameters": {
            "TargetSubnetId": {"Type": "AWS::EC2::Subnet::Id", "Description": "REPLACE with your actual target subnet"},
            "TargetSecurityGroupId": {"Type": "AWS::EC2::SecurityGroup::Id", "Description": "REPLACE with your actual target security group"},
        },
        "Resources": resources,
    }


# ─── Unified entry point ──────────────────────────────────────────────────────

# Function: generate_iac
def generate_iac(report: dict, provider: str, iac_format: str, server_names: Optional[list[str]] = None) -> tuple[str, str]:
    """
    Returns (content, content_type). iac_format: 'terraform' | 'arm' | 'cloudformation'.
    """
    provider = provider.lower()
    iac_format = iac_format.lower()

    if iac_format == "terraform":
        return generate_terraform(report, provider, server_names), "text/plain"
    if iac_format == "arm":
        if provider != "azure":
            raise ValueError("ARM templates are Azure-specific; use 'terraform' for other providers")
        return json.dumps(generate_arm_template(report, server_names), indent=2), "application/json"
    if iac_format == "cloudformation":
        if provider != "aws":
            raise ValueError("CloudFormation templates are AWS-specific; use 'terraform' for other providers")
        return json.dumps(generate_cloudformation(report, server_names), indent=2), "application/json"

    raise ValueError(f"Unsupported iac_format: {iac_format}")
